
import { StarSystem, Planet, Moon, BlackHole } from '../../../utils/galaxyGenerator';

export interface GalaxyLayoutBaseProps {
  galaxySeed: number;
  numSystems: number;
  numBlackHoles: number;
  binaryFrequency: number;
  trinaryFrequency: number;
  showDustLanes: boolean;
  showCosmicDust: boolean;
  showBlackHoles?: boolean;
  dustLaneParticles: number;
  cosmicDustParticles: number;
  dustLaneOpacity: number;
  cosmicDustOpacity: number;
  dustLaneColorIntensity: number;
  cosmicDustColorIntensity: number;
  jumpLaneOpacity: number;
  greenPathOpacity: number;
  selectedSystem: StarSystem | null;
  selectedStar: 'primary' | 'binary' | 'trinary';
  exploredSystems: Map<string, any>;
  explorationHistory: any[];
  highlightedBodyId: string | null;
  shipStats: any;
  currentSystemId: string | null;
  exploredSystemIds: Set<string>;
  travelHistory: string[];
  getJumpableSystemIds: (fromSystem: StarSystem | BlackHole, allSystems: StarSystem[], allBlackHoles?: BlackHole[]) => string[];
  getScannerRangeSystemIds: (fromSystem: StarSystem | BlackHole, allSystems: StarSystem[], allBlackHoles?: BlackHole[]) => string[];
  isSystemExplored: (systemId: string) => boolean;
  canSystemBeExplored: (systemId: string) => boolean;
  getSystemExplorationStatus: (systemId: string) => any;
  onSystemSelect: (system: StarSystem) => void;
  onStarSelect: (star: 'primary' | 'binary' | 'trinary') => void;
  onBodySelect: (body: Planet | Moon | null) => void;
  onBeginExploration: () => void;
  onResetExploration: () => void;
  onRepairHull: (cost: number) => void;
  onRepairShields: (cost: number) => void;
  onRepairCombatSystems: (cost: number) => void;
  onOpenMarket: () => void;
  onJumpToSystem: (systemId: string) => void;
  onUpdateShipName: (newName: string) => void;
  canJumpToSelected: boolean;
  onBlackHoleJumpBoost: (jumpData: { mode: 'local' | 'newGalaxy' | 'knownGalaxy'; seed?: number }) => void;
  allSystems: StarSystem[];
  allBlackHoles: BlackHole[];
}
